# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-03 23:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidatos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('candidatos', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='candidatos.Candidato')),
                ('data', models.DateTimeField(verbose_name='date published')),
                ('descricao', models.TextField()),
            ],
        ),
    ]
